// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqxRnspWEcGxSxBn-aLSjT_NZ-HZc7bgU',
    appId: '1:774110096656:web:113c8eaac177b2c4d50995',
    messagingSenderId: '774110096656',
    projectId: 'fish-e-commerce-dd83e',
    authDomain: 'fish-e-commerce-dd83e.firebaseapp.com',
    storageBucket: 'fish-e-commerce-dd83e.appspot.com',
    measurementId: 'G-VM86BN49LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGUCOr7ra5eM23lxsEBoACs-4vBiPn8ho',
    appId: '1:774110096656:android:b83c5d03ddf3d037d50995',
    messagingSenderId: '774110096656',
    projectId: 'fish-e-commerce-dd83e',
    storageBucket: 'fish-e-commerce-dd83e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqT5b2q5m8aHl7Qkdkfa1iOYmzpQ16xlc',
    appId: '1:774110096656:ios:b00a92bc40e1708cd50995',
    messagingSenderId: '774110096656',
    projectId: 'fish-e-commerce-dd83e',
    storageBucket: 'fish-e-commerce-dd83e.appspot.com',
    androidClientId: '774110096656-ua74vjhrj5e8hm4vmps30g3cskhjtcnq.apps.googleusercontent.com',
    iosClientId: '774110096656-hdenvf0c40aqqltrsikp8khsom5fo57t.apps.googleusercontent.com',
    iosBundleId: 'com.example.trungtamgiasu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqT5b2q5m8aHl7Qkdkfa1iOYmzpQ16xlc',
    appId: '1:774110096656:ios:0795bce09d155209d50995',
    messagingSenderId: '774110096656',
    projectId: 'fish-e-commerce-dd83e',
    storageBucket: 'fish-e-commerce-dd83e.appspot.com',
    androidClientId: '774110096656-ua74vjhrj5e8hm4vmps30g3cskhjtcnq.apps.googleusercontent.com',
    iosClientId: '774110096656-39ujq48j4befs0u7ea1a6tgnlrjdjs1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.trungtamgiasu.RunnerTests',
  );
}
